method CONSTRUCTOR ##ADT_SUPPRESS_GENERATION.
CALL METHOD SUPER->CONSTRUCTOR
EXPORTING
PREVIOUS = PREVIOUS
.
me->MESSAGES = MESSAGES .
clear me->textid.
if textid is initial.
  IF_T100_MESSAGE~T100KEY = Y00CACX_DOCX_RENDER_S .
else.
  IF_T100_MESSAGE~T100KEY = TEXTID.
endif.
endmethod.