PROCESS BEFORE OUTPUT.

MODULE %_INIT_PBO.

MODULE %_PBO_REPORT.

MODULE %_PF_STATUS.

MODULE %_S_TRKORR.

MODULE %_SO_KREP.

MODULE %_SO_KBSP.

MODULE %_SO_KWDA.

MODULE %_END_OF_PBO.

PROCESS AFTER INPUT.

  MODULE %_BACK AT EXIT-COMMAND.

  MODULE %_INIT_PAI.

CHAIN.
  FIELD P_DOCO  .
  FIELD P_DOCP  .
  FIELD P_DOCT  .
    MODULE %_RADIOBUTTON_GROUP_3                             .
ENDCHAIN.


CHAIN.
  FIELD P_DOCO  .
  FIELD P_DOCP  .
  FIELD P_DOCT  .
    MODULE %_BLOCK_1000000.
ENDCHAIN.

FIELD !P_OBJTYP MODULE %_P_OBJTYP .

FIELD !P_OBJECT MODULE %_P_OBJECT .

FIELD !P_PACKAG MODULE %_P_PACKAG .

CHAIN.
  FIELD  S_TRKORR-LOW.
  MODULE %_S_TRKORR.
ENDCHAIN.


CHAIN.
  FIELD P_OBJTYP .
  FIELD P_OBJECT .
  FIELD P_PACKAG .
  FIELD  S_TRKORR-LOW.
    MODULE %_BLOCK_1000009.
ENDCHAIN.

CHAIN.
  FIELD P_REDCX .
  FIELD P_REOLE .
  FIELD P_REXML .
    MODULE %_RADIOBUTTON_GROUP_RNDR                          .
ENDCHAIN.

CHAIN.
  FIELD P_LOCAL .
  FIELD P_APPL  .
    MODULE %_RADIOBUTTON_GROUP_RFIL                          .
ENDCHAIN.

FIELD !P_L_FILE MODULE %_P_L_FILE .

FIELD !P_A_FILE MODULE %_P_A_FILE .


CHAIN.
  FIELD P_LOCAL .
  FIELD P_APPL  .
  FIELD P_L_FILE .
  FIELD P_A_FILE .
    MODULE %_BLOCK_1000026.
ENDCHAIN.

FIELD !P_OPTECH MODULE %_P_OPTECH .

FIELD !P_EMPTY1 MODULE %_P_EMPTY1 .

FIELD !P_OPSELS MODULE %_P_OPSELS .

FIELD !P_OPOSCR MODULE %_P_OPOSCR .

FIELD !P_OPMCOM MODULE %_P_OPMCOM .

FIELD !P_OPINTF MODULE %_P_OPINTF .

CHAIN.
  FIELD  SO_KREP-LOW.
  MODULE %_SO_KREP.
ENDCHAIN.

CHAIN.
  FIELD  SO_KBSP-LOW.
  MODULE %_SO_KBSP.
ENDCHAIN.

CHAIN.
  FIELD  SO_KWDA-LOW.
  MODULE %_SO_KWDA.
ENDCHAIN.


CHAIN.
  FIELD  SO_KREP-LOW.
  FIELD  SO_KBSP-LOW.
  FIELD  SO_KWDA-LOW.
    MODULE %_BLOCK_1000063.
ENDCHAIN.


CHAIN.
  FIELD P_REDCX .
  FIELD P_REOLE .
  FIELD P_REXML .
  FIELD P_LOCAL .
  FIELD P_APPL  .
  FIELD P_L_FILE .
  FIELD P_A_FILE .
  FIELD P_OPTECH .
  FIELD P_EMPTY1 .
  FIELD P_OPSELS .
  FIELD P_OPOSCR .
  FIELD P_OPMCOM .
  FIELD P_OPINTF .
  FIELD  SO_KREP-LOW.
  FIELD  SO_KBSP-LOW.
  FIELD  SO_KWDA-LOW.
    MODULE %_BLOCK_1000015.
ENDCHAIN.

CHAIN.
  FIELD P_DOCO  .
  FIELD P_DOCP  .
  FIELD P_DOCT  .
  FIELD P_OBJTYP .
  FIELD P_OBJECT .
  FIELD P_PACKAG .
  FIELD  S_TRKORR-LOW.
  FIELD P_REDCX .
  FIELD P_REOLE .
  FIELD P_REXML .
  FIELD P_LOCAL .
  FIELD P_APPL  .
  FIELD P_L_FILE .
  FIELD P_A_FILE .
  FIELD P_OPTECH .
  FIELD P_EMPTY1 .
  FIELD P_OPSELS .
  FIELD P_OPOSCR .
  FIELD P_OPMCOM .
  FIELD P_OPINTF .
  FIELD  SO_KREP-LOW.
  FIELD  SO_KBSP-LOW.
  FIELD  SO_KWDA-LOW.
  MODULE %_END_OF_SCREEN.
  MODULE %_OK_CODE_1000.
ENDCHAIN.

PROCESS ON VALUE-REQUEST.
  FIELD P_OBJTYP MODULE %_P_OBJTYP_VAL .
  FIELD P_OBJECT MODULE %_P_OBJECT_VAL .
  FIELD S_TRKORR-LOW MODULE %_S_TRKORR-LOW_VAL .
  FIELD P_L_FILE MODULE %_P_L_FILE_VAL .