PROCESS BEFORE OUTPUT.

MODULE %_INIT_PBO.

MODULE %_PBO_REPORT.

MODULE %_PF_STATUS.

MODULE %_END_OF_PBO.

PROCESS AFTER INPUT.

  MODULE %_BACK AT EXIT-COMMAND.

  MODULE %_INIT_PAI.

FIELD !PA_WFKEY MODULE %_PA_WFKEY .

FIELD !PA_LANGU MODULE %_PA_LANGU .

CHAIN.
  FIELD PA_WFKEY .
  FIELD PA_LANGU .
  MODULE %_END_OF_SCREEN.
  MODULE %_OK_CODE_1000.
ENDCHAIN.

PROCESS ON VALUE-REQUEST.
  FIELD PA_WFKEY MODULE %_PA_WFKEY_VAL .