*&---------------------------------------------------------------------*
*&  Include           ZKCT_ABAP_DOC_SEL
*&---------------------------------------------------------------------*
* --> ZOLDOSP (13.01.2014 09:59:46): *************************
*SELECTION-SCREEN SKIP 7.
* <-- konec úpravy ******************************************

SELECTION-SCREEN BEGIN OF BLOCK obj WITH FRAME TITLE text-obj.
SELECTION-SCREEN BEGIN OF line.
PARAMETERS p_doco TYPE c RADIOBUTTON GROUP 3 USER-COMMAND updown.
SELECTION-SCREEN comment 5(20) FOR FIELD p_doco .
SELECTION-SCREEN PUSHBUTTON 38(25) pb_wf USER-COMMAND WF_DOC.
SELECTION-SCREEN END OF line.

PARAMETERS p_docp TYPE c RADIOBUTTON GROUP 3 DEFAULT 'X'.
PARAMETERS p_doct TYPE c RADIOBUTTON GROUP 3.
SELECTION-SCREEN END OF BLOCK obj.

SELECTION-SCREEN BEGIN OF BLOCK opt WITH FRAME TITLE text-opt.
PARAMETERS p_objtyp     TYPE  ko100-object MODIF ID obj.
PARAMETERS p_object     TYPE string MODIF ID obj.
PARAMETERS p_packag     TYPE tadir-devclass MODIF ID pkg DEFAULT 'Y00CAPKG_ABAPDOC'.

SELECT-OPTIONS s_trkorr FOR e071-trkorr NO INTERVALS NO-EXTENSION MODIF ID trn DEFAULT 'D5AK900281'.

SELECTION-SCREEN END OF BLOCK opt.

* Output document options
SELECTION-SCREEN BEGIN OF BLOCK oop WITH FRAME TITLE text-oop.

SELECTION-SCREEN: BEGIN OF LINE,
                    COMMENT 1(31) text-s06 FOR FIELD p_reole.
PARAMETERS:       p_redcx RADIOBUTTON GROUP rndr USER-COMMAND chtypefile DEFAULT 'X'.
SELECTION-SCREEN:   COMMENT (10) text-s08.
PARAMETERS:       p_reole RADIOBUTTON GROUP rndr .
SELECTION-SCREEN:   COMMENT (15) text-s07.
PARAMETERS:       p_rexml RADIOBUTTON GROUP rndr.
SELECTION-SCREEN:   COMMENT (25) text-s09.
SELECTION-SCREEN: END OF LINE.

SELECTION-SCREEN SKIP.
* Output file
SELECTION-SCREEN BEGIN OF BLOCK ofi WITH FRAME TITLE text-ofi.

SELECTION-SCREEN: BEGIN OF LINE.
PARAMETERS:       p_local RADIOBUTTON GROUP rfil USER-COMMAND ch_server DEFAULT 'X'.
SELECTION-SCREEN:   COMMENT (20) text-f01.
SELECTION-SCREEN:   COMMENT 30(10) text-f03 MODIF ID l_f.
PARAMETER p_l_file(300) LOWER CASE TYPE c MODIF ID l_f.
SELECTION-SCREEN: END OF LINE.

SELECTION-SCREEN: BEGIN OF LINE.
PARAMETERS:       p_appl RADIOBUTTON GROUP rfil MODIF ID a_r.
SELECTION-SCREEN:   COMMENT (20) text-f02 MODIF ID a_r.
SELECTION-SCREEN:   COMMENT 30(10) text-f03 MODIF ID a_f.
PARAMETER p_a_file(300) LOWER CASE TYPE c MODIF ID a_f.
SELECTION-SCREEN: END OF LINE.

SELECTION-SCREEN END OF BLOCK ofi.

SELECTION-SCREEN SKIP.
SELECTION-SCREEN BEGIN OF LINE.
PARAMETERS: p_optech AS CHECKBOX DEFAULT 'X'.
SELECTION-SCREEN COMMENT 5(30) FOR FIELD  p_optech .
SELECTION-SCREEN POSITION 35 .
PARAMETERS:   p_empty1 AS CHECKBOX.
SELECTION-SCREEN COMMENT 40(30) FOR FIELD  p_empty1 .
SELECTION-SCREEN END OF LINE.
*SELECTION-SCREEN SKIP  .
SELECTION-SCREEN BEGIN OF LINE.
PARAMETERS:  p_opsels AS CHECKBOX DEFAULT 'X'.
SELECTION-SCREEN COMMENT 5(30) FOR FIELD  p_opsels .
SELECTION-SCREEN POSITION 35 .
PARAMETERS:  p_oposcr AS CHECKBOX .
SELECTION-SCREEN COMMENT 40(30) FOR FIELD  p_oposcr .
SELECTION-SCREEN END OF LINE.
*SELECTION-SCREEN SKIP  .
SELECTION-SCREEN BEGIN OF LINE.
PARAMETERS:  p_opmcom AS CHECKBOX DEFAULT 'X'.
SELECTION-SCREEN COMMENT 5(30) FOR FIELD  p_opmcom .
SELECTION-SCREEN POSITION 35 .
PARAMETERS:  p_opintf AS CHECKBOX DEFAULT 'X'.
SELECTION-SCREEN COMMENT 40(30) FOR FIELD  p_opintf .
SELECTION-SCREEN END OF LINE.
SELECTION-SCREEN SKIP .
SELECTION-SCREEN BEGIN OF BLOCK kw1 WITH FRAME TITLE text-kw1.
SELECT-OPTIONS so_krep FOR g_text NO INTERVALS . "DEFAULT '#*&*' OPTION CP.
SELECT-OPTIONS so_kbsp FOR g_text NO INTERVALS ."DEFAULT '*navigation->*page*' OPTION CP .
SELECT-OPTIONS so_kwda FOR g_text NO INTERVALS .
SELECTION-SCREEN END OF BLOCK kw1.
SELECTION-SCREEN END OF BLOCK oop.